package consts

import "os"

const BotApiLink = "https://core.telegram.org/bots/api"
const PackageName = "github.com/Squirrel-Network/gobotapi"
const AGMessage = "// Code AutoGenerated; DO NOT EDIT."

var OutputFolder string
var FolderPermission os.FileMode
var CommonFields = []string{
	"from",
	"chat",
	"message",
}
