package consts

const BotApiLink = "https://core.telegram.org/bots/api"
const PackageName = "github.com/Squirrel-Network/gobotapi"
const AGMessage = "// Code AutoGenerated; DO NOT EDIT."

var OutputFolder string
